test

diff --git a/.github/workflows/push_python_package.yml b/.github/workflows/push_python_package.yml
--- a/.github/workflows/push_python_package.yml
+++ b/.github/workflows/push_python_package.yml
@@ -31,22 +31,22 @@ jobs:
               with:
                   python-version: 3.10 # TODO CREATE MULTIPLE VERSION OPTION HERE
 
-            - name: Compute Package version
-              id: compute-version
-              uses: ./.github/workflows/actions/compute_semantic_version/action.yml
-              with:
-                    github-token: ${{ secrets.TOKEN }}
+            # - name: Compute Package version
+            #   id: compute-version
+            #   uses: ./.github/workflows/actions/compute_semantic_version/action.yml
+            #   with:
+            #     github-token: ${{ secrets.TOKEN }}
 
-            - name: Set package version as output
-              run: |
-                PKG_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' pyproject.toml | head -n 1 || echo "unable-to-parse-package-name")
-                echo "PUSH_PYTHON_PACKAGE_NAME=$PKG_NAME" >> $GITHUB_ENV
+            # - name: Set package version as output
+            #   run: |
+            #     PKG_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' pyproject.toml | head -n 1 || echo "unable-to-parse-package-name")
+            #     echo "PUSH_PYTHON_PACKAGE_NAME=$PKG_NAME" >> $GITHUB_ENV
 
 
-            - name: Install dependencies
-              run: |
-                  python -m pip install --upgrade pip
-                  pip install setuptools wheel twine
+            # - name: Install dependencies
+            #   run: |
+            #       python -m pip install --upgrade pip
+            #       pip install setuptools wheel twine
 
             # - name: Build and publish
             #   run: |
